export type MuiV6Category =
  | 'Inputs'
  | 'Data display'
  | 'Feedback'
  | 'Surface'
  | 'Navigation'
  | 'Layout'
  | 'Lab'
  | 'Utils';

export type MuiGuideline = 'MD1' | 'MD2' | 'No guidelines' | 'Utility';
export type RavenSupportLevel = 'available' | 'themed' | 'guidance';

export interface MuiComponentLink {
  label: string;
  url: string;
}

export interface MuiV6CatalogItem {
  category: MuiV6Category;
  name: string;
  guideline: MuiGuideline;
  docsUrl: string;
  ravenSupport: RavenSupportLevel;
  ravenEquivalent: string;
  notes: string;
  summary?: string;
  importPath?: string[];
  composition?: string[];
  keyPoints?: string[];
  accessibility?: string[];
  apiLinks?: MuiComponentLink[];
}

export const MUI_V6_CATALOG_URL = 'https://v6.mui.com/material-ui/all-components/';

export const muiV6Catalog: MuiV6CatalogItem[] = [
  {
    category: 'Inputs',
    name: 'Autocomplete',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-autocomplete/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenAutocomplete',
    notes: 'Use Raven spacing, rounded outlined fields, and Source Sans 3 for searchable selection patterns.',
  },
  {
    category: 'Inputs',
    name: 'Button',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-button/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenButton / RavenIconButton',
    notes: 'Pill-radius buttons with purple palette, Source Sans 3 typography, uppercase labels, and loading state support. Includes RavenIconButton wrapper with loading convenience prop.',
  },
  {
    category: 'Inputs',
    name: 'Button Group',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-button-group/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiButtonGroup under ravenNearMissTheme',
    notes: 'Useful for compact action clusters where Raven keeps shared rounded corners and soft purple borders.',
  },
  {
    category: 'Inputs',
    name: 'Checkbox',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-checkbox/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenCheckbox',
    notes: 'Selected states should remain purple-led with explicit labels and helper text for accessibility.',
  },
  {
    category: 'Inputs',
    name: 'Floating Action Button',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-floating-action-button/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiFab under ravenNearMissTheme',
    notes: 'Reserved for high-priority quick actions with Raven purple fill and high-contrast white icons.',
  },
  {
    category: 'Inputs',
    name: 'Radio Group',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-radio-button/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenRadioGroup',
    notes: 'Keep options vertically readable with Source Sans 3 and purple checked states.',
  },
  {
    category: 'Inputs',
    name: 'Rating',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-rating/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiRating under ravenNearMissTheme guidance',
    notes: 'When used, favor restrained semantic feedback states rather than decorative scoring.',
  },
  {
    category: 'Inputs',
    name: 'Select',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-select/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenSelect',
    notes: 'Use the Raven outlined field treatment with compact menu surfaces and clear labels.',
  },
  {
    category: 'Inputs',
    name: 'Slider',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-slider/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiSlider under ravenNearMissTheme',
    notes: 'Tracks should keep the Raven purple accent and larger thumb target for touch comfort.',
  },
  {
    category: 'Inputs',
    name: 'Switch',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-switch/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenSwitch',
    notes: 'Use for binary settings only, with purple selected states and descriptive labels.',
  },
  {
    category: 'Inputs',
    name: 'Text Field',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-text-field/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenTextField',
    notes: 'Outlined fields, 8px corners, purple focus states, and Source Sans 3 are the Raven defaults.',
  },
  {
    category: 'Inputs',
    name: 'Transfer List',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-transfer-list/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'Composite pattern, not yet wrapped',
    notes: 'Treat as a documented composite built from lists, buttons, and selection controls when needed.',
  },
  {
    category: 'Inputs',
    name: 'Toggle Button',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-toggle-button/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiToggleButton / ViewToggle',
    notes: 'Raven prefers pill toggles with subtle purple surfaces for segmented state switching.',
  },

  {
    category: 'Data display',
    name: 'Avatar',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-avatar/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenAvatar',
    notes: 'Use initials, semantic color fills, and the Source Sans 3 type scale for identity markers.',
  },
  {
    category: 'Data display',
    name: 'Badge',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-badge/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenBadge',
    notes: 'Badges should stay compact, high contrast, and secondary to the primary surface content.',
  },
  {
    category: 'Data display',
    name: 'Chip',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-chip/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenChip',
    notes: 'Use pill chips for status, filters, and metadata with semantic fills or outlined brand states.',
  },
  {
    category: 'Data display',
    name: 'Divider',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-divider/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenDivider',
    notes: 'Prefer soft neutral separators to preserve the light Raven surfaces.',
    summary: 'The Divider component provides a thin, unobtrusive line for grouping elements to reinforce visual hierarchy.',
    importPath: ["import Divider from '@mui/material/Divider';"],
    keyPoints: [
      'Supports fullWidth, inset, and middle variants for different spacing relationships.',
      'Use orientation="vertical" for side-by-side layouts, and add flexItem when the divider lives inside a flex container.',
      'Dividers can wrap text or chips, with textAlign controlling the alignment of inline content.',
      'When separating list rows, render the divider as an li with the component prop so the markup stays valid.',
    ],
    accessibility: [
      'A plain Divider is announced as a separator by assistive technology.',
      'Set aria-hidden="true" when the divider is purely decorative.',
      'When wrapping text or chips, prefer component="div" with role="presentation" so the wrapped content remains the primary semantic target.',
    ],
    apiLinks: [{ label: 'Divider API', url: 'https://v6.mui.com/material-ui/api/divider/' }],
  },
  {
    category: 'Data display',
    name: 'Icons',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/icons/',
    ravenSupport: 'guidance',
    ravenEquivalent: '@mui/icons-material usage guidance',
    notes: 'Use standard Material icons with Raven color tokens and avoid mixing icon families within a workflow.',
  },
  {
    category: 'Data display',
    name: 'Material Icons',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/material-icons/',
    ravenSupport: 'guidance',
    ravenEquivalent: '@mui/icons-material import catalog',
    notes: 'Keep icon choices semantically consistent and aligned with the existing Raven icon inventory.',
  },
  {
    category: 'Data display',
    name: 'List',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-list/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenList',
    notes: 'Use padded list rows with rounded hover states and readable icon-to-text spacing.',
  },
  {
    category: 'Data display',
    name: 'Table',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-table/',
    ravenSupport: 'available',
    ravenEquivalent: 'DataTable',
    notes: 'Raven tables use quiet borders, strong header typography, and status-aware cells for review workflows.',
  },
  {
    category: 'Data display',
    name: 'Tooltip',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-tooltip/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenTooltip',
    notes: 'Tooltips should remain brief, accessible, and visually subordinate to the parent control.',
  },
  {
    category: 'Data display',
    name: 'Typography',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-typography/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenTypography',
    notes: 'Source Sans 3 font, full MUI type scale (h1–h6, subtitle1/2, body1/2, button, caption, overline) plus custom body1Bold and tableHeader variants. Raven purple brand colors and WCAG-compliant heading hierarchy.',
  },

  {
    category: 'Feedback',
    name: 'Alert',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-alert/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenAlert',
    notes: 'Use semantic fills with strong contrast and concise action-oriented copy.',
  },
  {
    category: 'Feedback',
    name: 'Backdrop',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-backdrop/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiBackdrop under ravenNearMissTheme',
    notes: 'Backdrop overlays should feel light and unobtrusive while preserving focus on the active surface.',
  },
  {
    category: 'Feedback',
    name: 'Dialog',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-dialog/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenDialog',
    notes: 'Dialogs use large-radius paper, focused action hierarchy, and clear escape paths.',
  },
  {
    category: 'Feedback',
    name: 'Progress',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-progress/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenLinearProgress / RavenCircularProgress',
    notes: 'Progress indicators should favor purple accents with quiet track surfaces.',
  },
  {
    category: 'Feedback',
    name: 'Skeleton',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-skeleton/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenSkeleton',
    notes: 'Use soft purple-tinted placeholders to preserve the Raven surface rhythm during loading.',
  },
  {
    category: 'Feedback',
    name: 'Snackbar',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-snackbar/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenSnackbar',
    notes: 'Snackbars should feel like floating notifications, not buttons, with clear severity states.',
  },

  {
    category: 'Surface',
    name: 'Accordion',
    guideline: 'MD1',
    docsUrl: 'https://v6.mui.com/material-ui/react-accordion/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenAccordion',
    notes: 'Use compact outlined accordions for supporting detail rather than primary workflow steps.',
    summary: 'The Accordion component lets users show and hide sections of related content on a page.',
    importPath: [
      "import Accordion from '@mui/material/Accordion';",
      "import AccordionSummary from '@mui/material/AccordionSummary';",
      "import AccordionDetails from '@mui/material/AccordionDetails';",
    ],
    composition: [
      'Accordion: wrapper for the grouped section.',
      'Accordion Summary: interactive header that expands or collapses content.',
      'Accordion Details: content region for the expanded state.',
      'Accordion Actions: optional footer container for action buttons.',
    ],
    keyPoints: [
      'Use the expandIcon prop on AccordionSummary to swap the disclosure icon while keeping the built-in rotation animation.',
      'defaultExpanded covers the common uncontrolled case, while expanded supports fully controlled accordions.',
      'Use slots.transition and slotProps.transition to customize the expansion transition or unmount heavy content on exit.',
      'Adjust slotProps.heading.component when the default h3 heading does not fit the page heading hierarchy.',
    ],
    accessibility: [
      'Set id and aria-controls on AccordionSummary so the generated region and button relationship stays explicit.',
      'Keep heading levels consistent by updating slotProps.heading.component when the accordion sits deeper in the document outline.',
      'Follow the WAI-ARIA accordion pattern for keyboard and announcement behavior.',
    ],
    apiLinks: [
      { label: 'Accordion API', url: 'https://v6.mui.com/material-ui/api/accordion/' },
      { label: 'Accordion Summary API', url: 'https://v6.mui.com/material-ui/api/accordion-summary/' },
      { label: 'Accordion Details API', url: 'https://v6.mui.com/material-ui/api/accordion-details/' },
      { label: 'Accordion Actions API', url: 'https://v6.mui.com/material-ui/api/accordion-actions/' },
    ],
  },
  {
    category: 'Surface',
    name: 'App Bar',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-app-bar/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiAppBar / MobileAppShell header treatment',
    notes: 'Raven app bars should remain light, border-led, and secondary to the page content container.',
    summary: 'The App Bar displays information and actions relating to the current screen and is commonly used for branding, titles, navigation, and contextual actions.',
    importPath: [
      "import AppBar from '@mui/material/AppBar';",
      "import Toolbar from '@mui/material/Toolbar';",
    ],
    composition: [
      'AppBar: positioned surface container for top or bottom navigation treatments.',
      'Toolbar: spacing and height wrapper for title, navigation, search, and action controls.',
    ],
    keyPoints: [
      'Use AppBar for screen-level branding, titles, menus, and search entry points.',
      'Prefer position="sticky" when possible; fixed app bars need an offset element or theme.mixins.toolbar so page content is not hidden behind the bar.',
      'useScrollTrigger supports hide-on-scroll and elevate-on-scroll patterns when the header should respond to reading behavior.',
      'In dark mode, enableColorOnDark restores color-driven styling when the default dark treatment is too muted.',
    ],
    apiLinks: [
      { label: 'App Bar API', url: 'https://v6.mui.com/material-ui/api/app-bar/' },
      { label: 'Toolbar API', url: 'https://v6.mui.com/material-ui/api/toolbar/' },
      { label: 'useScrollTrigger API', url: 'https://v6.mui.com/material-ui/react-app-bar/#scrolling' },
    ],
  },
  {
    category: 'Surface',
    name: 'Card',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-card/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenCard',
    notes: 'Cards use generous radius, soft borders, and content-first spacing to echo Figma surfaces.',
    summary: 'Cards contain content and actions about a single subject and can combine headers, media, primary actions, and supporting controls.',
    importPath: [
      "import Card from '@mui/material/Card';",
      "import CardHeader from '@mui/material/CardHeader';",
      "import CardContent from '@mui/material/CardContent';",
      "import CardMedia from '@mui/material/CardMedia';",
      "import CardActions from '@mui/material/CardActions';",
      "import CardActionArea from '@mui/material/CardActionArea';",
    ],
    composition: [
      'Card: surface container for a single topic.',
      'CardHeader: optional title, subheader, avatar, and action slot in the header region.',
      'CardContent: body copy and primary information with consistent padding.',
      'CardMedia: image, video, or other media — use component="img" for semantic HTML.',
      'CardActions: footer container for supplemental buttons, kept outside CardActionArea.',
      'CardActionArea: wraps the interactive region when the whole card is a single clickable target.',
    ],
    keyPoints: [
      'Set variant="outlined" when the design calls for a flatter container instead of elevated depth.',
      'Wrap the primary interactive region in CardActionArea when the whole card should behave like a link or expandable target.',
      'Keep supplemental footer buttons outside the CardActionArea to avoid overlapping hit targets.',
      'Use component="img" on CardMedia when a semantic img element is more appropriate than a CSS background-image container.',
      'RavenCard exposes a media prop (image URL), mediaHeight, actionArea, and onClick for common patterns without composing sub-components manually.',
      'Use the variant prop ("elevation" | "outlined") instead of the deprecated elevated boolean.',
    ],
    accessibility: [
      'CardActionArea renders a <button> by default — add a meaningful aria-label when the card title is not descriptive enough.',
      'Avoid nesting interactive elements (links, buttons) inside a CardActionArea; place them in CardActions instead.',
      'CardMedia with component="img" requires a non-empty alt attribute for screen readers.',
      'Use the component prop to render CardActionArea as an <a> tag when the card navigates to another page.',
    ],
    apiLinks: [
      { label: 'Card API', url: 'https://v6.mui.com/material-ui/api/card/' },
      { label: 'Card Header API', url: 'https://v6.mui.com/material-ui/api/card-header/' },
      { label: 'Card Content API', url: 'https://v6.mui.com/material-ui/api/card-content/' },
      { label: 'Card Actions API', url: 'https://v6.mui.com/material-ui/api/card-actions/' },
      { label: 'Card Action Area API', url: 'https://v6.mui.com/material-ui/api/card-action-area/' },
      { label: 'Card Media API', url: 'https://v6.mui.com/material-ui/api/card-media/' },
    ],
  },
  {
    category: 'Surface',
    name: 'Paper',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-paper/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiPaper under ravenNearMissTheme',
    notes: 'Paper surfaces should inherit Raven corner radius and remain visually lighter than default Material.',
    summary: 'The Paper component is a container for displaying content on an elevated surface and uses the theme elevation scale to express depth.',
    importPath: ["import Paper from '@mui/material/Paper';"],
    keyPoints: [
      'Use elevation values from 0 to 24 to communicate hierarchy through theme shadows.',
      'In dark mode, higher elevation also lightens the background with a translucent overlay.',
      'Set variant="outlined" to render a flat bordered paper without shadow.',
      'Paper uses rounded corners by default; add square to remove the radius when the layout needs hard edges.',
    ],
    apiLinks: [{ label: 'Paper API', url: 'https://v6.mui.com/material-ui/api/paper/' }],
  },

  {
    category: 'Navigation',
    name: 'Bottom Navigation',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-bottom-navigation/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiBottomNavigation under ravenNearMissTheme',
    notes: 'Use only on constrained mobile layouts and keep the active state clearly brand-led.',
  },
  {
    category: 'Navigation',
    name: 'Breadcrumbs',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-breadcrumbs/',
    ravenSupport: 'available',
    ravenEquivalent: 'BreadcrumbNav / MuiBreadcrumbs',
    notes: 'Breadcrumbs should stay terse and may include status metadata where context improves navigation.',
  },
  {
    category: 'Navigation',
    name: 'Drawer',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-drawer/',
    ravenSupport: 'available',
    ravenEquivalent: 'ActivityDrawer / MuiDrawer',
    notes: 'Raven drawers favor soft left corners, light surfaces, and timeline-style supporting content.',
  },
  {
    category: 'Navigation',
    name: 'Link',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-link/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenLink',
    notes: 'Links should keep brand color emphasis without overpowering the surrounding reading flow.',
  },
  {
    category: 'Navigation',
    name: 'Menu',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-menu/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenMenu',
    notes: 'Menus should use compact rounded surfaces, subtle shadows, and icon-aware spacing.',
  },
  {
    category: 'Navigation',
    name: 'Pagination',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-pagination/',
    ravenSupport: 'available',
    ravenEquivalent: 'RavenPagination',
    notes: 'Keep pagination light, pill-shaped, and strongly visible in the selected state.',
  },
  {
    category: 'Navigation',
    name: 'Speed Dial',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-speed-dial/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiSpeedDial under ravenNearMissTheme',
    notes: 'Use sparingly for dense quick-action workflows where a floating action cluster is justified.',
  },
  {
    category: 'Navigation',
    name: 'Stepper',
    guideline: 'MD1',
    docsUrl: 'https://v6.mui.com/material-ui/react-stepper/',
    ravenSupport: 'available',
    ravenEquivalent: 'StatusStepper / MuiStepper',
    notes: 'Raven step flows emphasize status transitions and review progression over generic checkout patterns.',
  },
  {
    category: 'Navigation',
    name: 'Tabs',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-tabs/',
    ravenSupport: 'available',
    ravenEquivalent: 'TabNavigation / MuiTabs',
    notes: 'Supports Raven navigation tabs plus wrapped labels, full-width and centered layouts, scrollable tab sets, icon-only and icon-label tabs, icon positioning, link-style nav tabs, selection-follows-focus behavior, vertical orientation, and a segmented pill-style variant for high-emphasis view switching.',
  },

  {
    category: 'Layout',
    name: 'Box',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-box/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Box in Raven layout patterns',
    notes: 'Box is the core primitive behind AppShell and page compositions; keep spacing token-driven.',
  },
  {
    category: 'Layout',
    name: 'Container',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-container/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Container with Raven tokens',
    notes: 'Use only when a centered content rail is preferable to the full-width Near Miss shell.',
  },
  {
    category: 'Layout',
    name: 'Grid',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-grid/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Grid under Raven spacing rules',
    notes: 'Prefer 4px-based spacing and consistent card gutters when using classic grid layouts.',
  },
  {
    category: 'Layout',
    name: 'Grid v2',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-grid2/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Grid v2 under Raven spacing rules',
    notes: 'Use Grid v2 for newer layouts that benefit from simplified API and token-driven spacing.',
  },
  {
    category: 'Layout',
    name: 'Stack',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-stack/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Stack with Raven spacing tokens',
    notes: 'Stack is preferred for vertical or inline layout rhythm inside Raven cards and forms.',
  },
  {
    category: 'Layout',
    name: 'Image List',
    guideline: 'MD2',
    docsUrl: 'https://v6.mui.com/material-ui/react-image-list/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Image List with Raven surfaces',
    notes: 'Use for media-centric layouts only; it is not a primary Near Miss workflow primitive.',
  },

  {
    category: 'Lab',
    name: 'Masonry',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-masonry/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Lab Masonry',
    notes: 'Documented for future use; install MUI Lab before adding live Raven wrappers.',
  },
  {
    category: 'Lab',
    name: 'Timeline',
    guideline: 'No guidelines',
    docsUrl: 'https://v6.mui.com/material-ui/react-timeline/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Lab Timeline / ActivityTimelineItem',
    notes: 'Near Miss already uses custom activity timeline patterns, so the lab primitive is guidance-first.',
  },

  {
    category: 'Utils',
    name: 'Click-Away Listener',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-click-away-listener/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI ClickAwayListener',
    notes: 'Use to close menus, popovers, and layered controls without breaking keyboard accessibility.',
  },
  {
    category: 'Utils',
    name: 'CSS Baseline',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-css-baseline/',
    ravenSupport: 'available',
    ravenEquivalent: 'CssBaseline in app and Storybook preview',
    notes: 'CssBaseline is required to keep Raven typography and surface behavior consistent across stories.',
  },
  {
    category: 'Utils',
    name: 'Modal',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-modal/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiModal with Raven overlay guidance',
    notes: 'Use when dialog semantics are not appropriate but layered focus management is still required.',
  },
  {
    category: 'Utils',
    name: 'No SSR',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-no-ssr/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI NoSsr',
    notes: 'Documented for integration scenarios; not typically needed in the core Raven Storybook flows.',
  },
  {
    category: 'Utils',
    name: 'Popover',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-popover/',
    ravenSupport: 'themed',
    ravenEquivalent: 'MuiPopover with Raven paper styling',
    notes: 'Use for anchored contextual content that needs stronger structure than a tooltip.',
  },
  {
    category: 'Utils',
    name: 'Popper',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-popper/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Popper',
    notes: 'Use for low-level positioning needs where Popover or Menu is too opinionated.',
  },
  {
    category: 'Utils',
    name: 'Portal',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-portal/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI Portal',
    notes: 'Documented as an infrastructure primitive for overlays and detached rendering targets.',
  },
  {
    category: 'Utils',
    name: 'Textarea Autosize',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-textarea-autosize/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'TextareaAutosize / CommentInput',
    notes: 'Best for comment and note capture where multiline growth is more important than form chrome.',
  },
  {
    category: 'Utils',
    name: 'Transitions',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/transitions',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI transition helpers',
    notes: 'Use motion sparingly and keep it subordinate to clarity in operational workflows.',
  },
  {
    category: 'Utils',
    name: 'useMediaQuery',
    guideline: 'Utility',
    docsUrl: 'https://v6.mui.com/material-ui/react-use-media-query/',
    ravenSupport: 'guidance',
    ravenEquivalent: 'MUI useMediaQuery hook',
    notes: 'Use for responsive behavioral shifts, especially when adapting desktop layouts to mobile shells.',
  },
];

export const muiV6Categories: MuiV6Category[] = [
  'Inputs',
  'Data display',
  'Feedback',
  'Surface',
  'Navigation',
  'Layout',
  'Lab',
  'Utils',
];
